# Generated by Django 4.1.3 on 2022-12-12 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.CharField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('url', models.URLField(default=None, validators=[django.core.validators.URLValidator])),
                ('imageUrl', models.URLField(default=None, validators=[django.core.validators.URLValidator])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('youtube', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.youtubedata')),
            ],
        ),
    ]
