# Generated by Django 4.1.3 on 2022-12-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_user', 'can add a new user'),)},
        ),
    ]
