# Generated by Django 4.1.3 on 2022-12-19 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'name should have less than 50 characters'), django.core.validators.MinLengthValidator(3, 'name should have at least 3 characters')]),
        ),
    ]
