# Generated by Django 4.1.3 on 2023-01-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_youtubedata_imageurl_youtubedata_channel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubedata',
            name='url',
        ),
    ]
