# Generated by Django 4.1.3 on 2023-01-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_youtubedata_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(default=None)),
                ('youtube_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.youtubedata')),
            ],
        ),
    ]
