# Generated by Django 4.1.3 on 2023-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='path',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
