# Generated by Django 4.1.3 on 2023-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_youtubevideo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='length',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
